name: Pylint

on: [push, release]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Pylint tests
    steps:
    - uses: actions/checkout@v2
    - name: Linter Test
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
